In [1]:
# data preprocessing

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

# load the dataset
with open('sherlock.txt','r') as file:
    text = file.read().lower()
    
# Tokenize the text - creating indexes for word
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
total_words = len(tokenizer.word_index)+1
total_words

8200

In [2]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'i': 3,
 'to': 4,
 'of': 5,
 'a': 6,
 'in': 7,
 'that': 8,
 'it': 9,
 'he': 10,
 'you': 11,
 'was': 12,
 'his': 13,
 'is': 14,
 'my': 15,
 'have': 16,
 'as': 17,
 'with': 18,
 'had': 19,
 'which': 20,
 'at': 21,
 'for': 22,
 'but': 23,
 'me': 24,
 'not': 25,
 'be': 26,
 'we': 27,
 'from': 28,
 'there': 29,
 'this': 30,
 'said': 31,
 'upon': 32,
 'so': 33,
 'holmes': 34,
 'him': 35,
 'her': 36,
 'she': 37,
 "'": 38,
 'very': 39,
 'your': 40,
 'been': 41,
 'all': 42,
 'on': 43,
 'no': 44,
 'what': 45,
 'one': 46,
 'then': 47,
 'were': 48,
 'by': 49,
 'are': 50,
 'an': 51,
 'would': 52,
 'out': 53,
 'when': 54,
 'up': 55,
 'man': 56,
 'could': 57,
 'has': 58,
 'do': 59,
 'into': 60,
 'mr': 61,
 'who': 62,
 'little': 63,
 'will': 64,
 'if': 65,
 'some': 66,
 'now': 67,
 'see': 68,
 'down': 69,
 'should': 70,
 'our': 71,
 'or': 72,
 'they': 73,
 'may': 74,
 'well': 75,
 'am': 76,
 'us': 77,
 'over': 78,
 'more': 79,
 'think': 80,
 'room': 81,
 'know': 82,
 'shall': 83

In [3]:
# create input sequences
input_sequences = []
for line in text.split('\n'):
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

In [4]:
input_sequences

[[1, 1561],
 [1, 1561, 5],
 [1, 1561, 5, 129],
 [1, 1561, 5, 129, 34],
 [647, 4498],
 [647, 4498, 4499],
 [226, 5],
 [226, 5, 1562],
 [6, 827],
 [6, 827, 7],
 [6, 827, 7, 871],
 [1, 234],
 [1, 234, 462],
 [1, 234, 462, 648],
 [6, 110],
 [6, 110, 5],
 [6, 110, 5, 2072],
 [1, 678],
 [1, 678, 1360],
 [1, 678, 1360, 499],
 [1, 294],
 [1, 294, 949],
 [1, 294, 949, 872],
 [1, 56],
 [1, 56, 18],
 [1, 56, 18, 1],
 [1, 56, 18, 1, 1014],
 [1, 56, 18, 1, 1014, 873],
 [1, 577],
 [1, 577, 5],
 [1, 577, 5, 1],
 [1, 577, 5, 1, 423],
 [1, 577, 5, 1, 423, 1361],
 [1, 577],
 [1, 577, 5],
 [1, 577, 5, 1],
 [1, 577, 5, 1, 1785],
 [1, 577, 5, 1, 1785, 763],
 [1, 577],
 [1, 577, 5],
 [1, 577, 5, 1],
 [1, 577, 5, 1, 3185],
 [1, 577, 5, 1, 3185, 649],
 [1, 577],
 [1, 577, 5],
 [1, 577, 5, 1],
 [1, 577, 5, 1, 764],
 [1, 577, 5, 1, 764, 1246],
 [1, 577],
 [1, 577, 5],
 [1, 577, 5, 1],
 [1, 577, 5, 1, 2073],
 [1, 577, 5, 1, 2073, 394],
 [1, 577],
 [1, 577, 5],
 [1, 577, 5, 1],
 [1, 577, 5, 1, 828],
 [1, 577, 5, 

In [5]:
# padding the sequences
max_sequence_len = max([len(x) for x in input_sequences])
max_sequence_len

18

In [6]:
input_sequences = np.array(pad_sequences(input_sequences,maxlen=max_sequence_len))
input_sequences

array([[   0,    0,    0, ...,    0,    1, 1561],
       [   0,    0,    0, ...,    1, 1561,    5],
       [   0,    0,    0, ..., 1561,    5,  129],
       ...,
       [   0,    0,    0, ...,    1, 8198, 8199],
       [   0,    0,    0, ..., 8198, 8199, 3187],
       [   0,    0,    0, ..., 8199, 3187, 3186]],
      shape=(96314, 18), dtype=int32)

In [7]:
# create predictor and label

import tensorflow as tf
x,y = input_sequences[:,:-1],input_sequences[:,-1]

In [8]:
print(x)
print()
print("y prining")
print(y)

[[   0    0    0 ...    0    0    1]
 [   0    0    0 ...    0    1 1561]
 [   0    0    0 ...    1 1561    5]
 ...
 [   0    0    0 ...   28    1 8198]
 [   0    0    0 ...    1 8198 8199]
 [   0    0    0 ... 8198 8199 3187]]

y prining
[1561    5  129 ... 8199 3187 3186]


In [9]:
y = tf.keras.utils.to_categorical(y,num_classes=total_words)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(96314, 8200))

In [10]:
# spliting the data into training and testing sets

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2)

In [11]:
# trainn our LSTM RNN
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout
from tensorflow.keras import Input

# define the model

model = Sequential([
    Input(shape=(max_sequence_len,)),
    Embedding(total_words, 100),
    LSTM(150, return_sequences=True),
    Dropout(0.2),
    LSTM(100),
    Dense(total_words, activation='softmax')
])


# compile the model
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 18, 100)        │       820,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 18, 150)        │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 18, 150)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 100)            │       100,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 8200)           │       828,200 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,899,200 (7.24 MB)

 Trainable params: 1,899,200 (7.24 MB)

 Non-trainable params: 0 (0.00 B)

In [12]:
# train the model
history = model.fit(x_train,y_train , epochs=150,validation_data=(x_test,y_test),verbose=1)

Epoch 1/150
2408/2408 ━━━━━━━━━━━━━━━━━━━━ 69s 27ms/step - accuracy: 0.0602 - loss: 6.4311 - val_accuracy: 0.0664 - val_loss: 6.1923
Epoch 2/150
2408/2408 ━━━━━━━━━━━━━━━━━━━━ 71s 29ms/step - accuracy: 0.0830 - loss: 5.8628 - val_accuracy: 0.0926 - val_loss: 5.9831
Epoch 3/150
2408/2408 ━━━━━━━━━━━━━━━━━━━━ 81s 34ms/step - accuracy: 0.1057 - loss: 5.5609 - val_accuracy: 0.1125 - val_loss: 5.9156
Epoch 4/150
2408/2408 ━━━━━━━━━━━━━━━━━━━━ 77s 32ms/step - accuracy: 0.1198 - loss: 5.3369 - val_accuracy: 0.1177 - val_loss: 5.9079
Epoch 5/150
2408/2408 ━━━━━━━━━━━━━━━━━━━━ 86s 36ms/step - accuracy: 0.1296 - loss: 5.1561 - val_accuracy: 0.1203 - val_loss: 5.9590
Epoch 6/150
2408/2408 ━━━━━━━━━━━━━━━━━━━━ 71s 29ms/step - accuracy: 0.1373 - loss: 4.9981 - val_accuracy: 0.1258 - val_loss: 6.0199
Epoch 7/150
2408/2408 ━━━━━━━━━━━━━━━━━━━━ 87s 36ms/step - accuracy: 0.1447 - loss: 4.8494 - val_accuracy: 0.1289 - val_loss: 6.1035
Epoch 8/150
2408/2408 ━━━━━━━━━━━━━━━━━━━━ 93s 39ms/step - accuracy: 

In [13]:
# function to predict the next word
def predict_next_word(model,tokenizer,text,max_sequence_len):
    token_list = tokenizer.texts_to_sequences([text])[0]
    if len(token_list) >= max_sequence_len:
        token_list = token_list[-(max_sequence_len-1):] # ensure the sequence length matches max_sequence
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1,padding='pre')
    predicted = model.predict(token_list,verbose = 0)
    predicted_word_index = np.argmax(predicted,axis=1)
    for word,index in tokenizer.word_index.items():
        if index == predicted_word_index:
            return word
    return None
        

In [14]:
input_text = "To be ot not to be "
print("Input yext : {input_text}")
max_sequence_len = model.input_shape[1]+1
next_word = predict_next_word(model,tokenizer , input_text , max_sequence_len)
print(f"Next word prediction : {next_word}")
 
 
 
 

Input yext : {input_text}
Next word prediction : inhabited


In [15]:
# save the model
model.save("next_word_lstm_2.h5")
# save the tokenizer
import pickle
with open('tokenizer2.pickle','wb') as handle:
    pickle.dump(tokenizer, handle, protocol = pickle.HIGHEST_PROTOCOL)

In [18]:
input_text = "To be fucked "
print("Input yext : {input_text}")
max_sequence_len = model.input_shape[1]+1
next_word = predict_next_word(model,tokenizer , input_text , max_sequence_len)
print(f"Next word prediction : {next_word}")

Input yext : {input_text}
Next word prediction : almost
